---
title: "Human Activity Recognition using Wearable Sensor Technology"
subtitle: "626 Task 2"
author: ""
date: ""
output:
  word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA,
                      cache = TRUE)
```

# Load Packages

```{r}
library(tidyverse)
library(glmnet)
library(caret)
library(doMC)
```

# Import Data

```{r}
train = read.table('~/desktop/626 mid1/data/training_data.txt',header = T)
test = read.table('~/desktop/626 mid1/data/test_data.txt',header = T)
```

```{r}
train = train %>% 
  select(-subject) %>% 
  mutate(activity = ifelse(activity %in% 7:12,7,activity),
         activity = as.factor(activity))

test = test %>% 
  select(-subject)

table(train$activity)
```

# PCA

```{r}
PCA = prcomp(x = train %>% select(-activity))
lambda = PCA$sdev^2
prop = cumsum(lambda)/sum(lambda)
n_pc = min(which(prop>0.8))
PCA$x[,1:2] %>% 
  as.data.frame() %>% 
  mutate(activity = train$activity) %>% 
  ggplot(aes(x = PC1,y = PC2,color = activity)) +
  geom_point() +
  scale_color_brewer(palette = 'Set1') +
  theme_bw()
```

# Lasso

```{r}
x_train = train %>% select(-activity) %>% as.matrix()
y_train = train$activity
x_test = test %>% as.matrix()
set.seed(1)
registerDoMC(6)
cv_lasso = cv.glmnet(x = x_train,
                     y = y_train,
                     family = 'multinomial',
                     type.measure = 'class',
                     alpha = 1,
                     parallel = T)
```

```{r}
plot(cv_lasso)
```

```{r}
var_lasso1 = coef(cv_lasso)[[1]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso2 = coef(cv_lasso)[[2]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso3 = coef(cv_lasso)[[3]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso4 = coef(cv_lasso)[[4]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso5 = coef(cv_lasso)[[5]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso6 = coef(cv_lasso)[[6]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso7 = coef(cv_lasso)[[7]] %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'variable') %>% 
  slice(-1) %>% 
  filter(`1`!=0) %>% 
  pull(variable)
```

```{r}
var_lasso = c(var_lasso1,var_lasso2,var_lasso3,var_lasso4,var_lasso5,var_lasso6,var_lasso7)
var_lasso = unique(var_lasso)
```

```{r}
pre_lasso = predict(cv_lasso,newx = x_test,s = cv_lasso$lambda.1se,type = 'class')
pre_lasso = as.numeric(pre_lasso)
```

```{r}
# final_train = train %>% select(activity,all_of(var_lasso))
final_train = PCA$x[,1:n_pc] %>% as.data.frame() %>% mutate(activity = train$activity)
final_test = predict(PCA,newdata = test)
final_test = as.data.frame(final_test[,1:n_pc])
```

```{r}
set.seed(1)
my_control = trainControl(method = 'repeatedcv',
                          number = 5,
                          repeats = 10,
                          search = 'random')
f = as.formula('activity~.')
```

# Random Forest

```{r}
set.seed(1)
registerDoMC(6)
cv_RF = train(f,
              data = final_train,
              method = 'rf',
              metric = 'Accuracy',
              trControl = my_control,
              tuneLength = 30)
cv_RF$results
plot(cv_RF)
```

```{r}
set.seed(1)
registerDoMC(6)
final_RF = train(f,
                 data = final_train,
                 method = 'rf',
                 tuneGrid = cv_RF$bestTune)
pre_RF = predict(final_RF,newdata = final_test)
```

# XGBoost

```{r}
set.seed(1)
registerDoMC(6)
cv_XGBoost = train(f,
                   data = final_train,
                   method = 'xgbTree',
                   metric = 'Accuracy',
                   trControl = my_control,
                   tuneLength = 30)
cv_XGBoost$results
```

```{r}
set.seed(1)
registerDoMC(6)
final_XGBoost = train(f,
                      data = final_train,
                      method = 'xgbTree',
                      tuneGrid = cv_XGBoost$bestTune)
pre_XGBoost = predict(final_XGBoost,newdata = final_test)
```

# SVM

```{r}
set.seed(1)
registerDoMC(6)
cv_SVM = train(f,
               data = final_train,
               method = 'svmRadial',
               metric = 'Accuracy',
               trControl = my_control,
               tuneLength = 30)
cv_SVM$results
```

```{r}
set.seed(1)
registerDoMC(6)
final_SVM = train(f,
                  data = final_train,
                  method = 'svmRadial',
                  tuneGrid = cv_SVM$bestTune)
pre_SVM = predict(final_SVM,newdata = final_test)
```

# Neural Network

```{r}
set.seed(1)
registerDoMC(6)
cv_NNET = train(f,
                data = final_train,
                method = 'nnet',
                trace = F,
                metric = 'Accuracy',
                trControl = my_control,
                tuneLength = 30)
cv_NNET$results
```

```{r}
set.seed(1)
registerDoMC(6)
final_NNET = train(f,
                   data = final_train,
                   method = 'nnet',
                   trace = F,
                   tuneGrid = cv_NNET$bestTune)
pre_NNET = predict(final_NNET,newdata = final_test)
```

```{r}
tibble(Lasso = 1-min(cv_lasso$cvm),
       `Random Forest` = max(cv_RF$results$Accuracy),
       XGBoost = max(cv_XGBoost$results$Accuracy),
       SVM = max(cv_SVM$results$Accuracy),
       `Neural Network` = max(cv_NNET$results$Accuracy)) %>% 
  pivot_longer(cols = everything(),
               names_to = 'Algorithm',
               values_to = 'CV Accuracy')
```

```{r}
write.table(x = pre_lasso,'Lasso.txt',row.names = F,col.names = F)
write.table(x = pre_RF,'Random Forest.txt',row.names = F,col.names = F)
write.table(x = pre_XGBoost,'XGBoost.txt',row.names = F,col.names = F)
write.table(x = pre_SVM,'SVM.txt',row.names = F,col.names = F)
write.table(x = pre_NNET,'NNET.txt',row.names = F,col.names = F)
```

```{r}
write.table(x = pre_SVM,"/Users/mingruili/Desktop/multiclass_9982.txt",row.names = F,col.names = F,quote = FALSE)
```





